#!/usr/bin/python3
# SPDX-FileCopyrightText: 2025 Satoh-Narumi
# SPDX-License-Identifier: BSD-3-Clause

import os
import argparse
import sys
from PIL import Image

parser = argparse.ArgumentParser(description='画像ファイルの解像度、縦横比を変更できるコマンド。不可逆。',
                                     prog='gazo',
                                )
subparsers = parser.add_subparsers(
    dest='mode',
    required=True
)
parser_r = subparsers.add_parser('reso')
parser_s = subparsers.add_parser('size')
parser_g = subparsers.add_parser('get')

#以下状況によって使い分ける
parser_r.add_argument('location',type=str)
parser_r.add_argument('quality',default=100,type=int)
parser_r.add_argument('-util', choices=['info', 'debug'])

parser_s.add_argument('location',type=str)
parser_s.add_argument('width',type=int)
parser_s.add_argument('height',type=int)
parser_s.add_argument('-util', choices=['info', 'debug'])

parser_g.add_argument('location',type=str)
parser_g.add_argument('-util', choices=['info', 'debug'],required=False)

args = parser.parse_args()
    
filelocation = args.location
filename = os.path.basename(filelocation)
filesize_before = round(os.path.getsize(filelocation) / 1024 , 2)

if '.png' and '.gif' in filename:
    sys.exit("Unable to convert on this format.")

if not filelocation:
    sys.exit("Couldn't find on target file.")

if args.mode == "size":
    res_x = args.width
    res_y = args.height
    
    img_size_b = Image.open(filename)
    width_b, height_b = img_size_b.size
    img_resize = img_size_b.resize((res_x, res_y))
    resize_file = "resized_" + filename
    img_resize.save(resize_file)
    img_size_b.close()
        
    filesize_after_size=round(os.path.getsize(resize_file) / 1024, 2)
    img_size_a = Image.open(resize_file)
    width_a, height_a = img_size_a.size
    img_size_a.close()
        
    if(args.util == 'debug'):
        print(f"{width_a},{height_a},{filesize_after_size}")
    elif(args.util == 'info'):
        print(f"size_of_file:{width_b}x{height_b}>{width_a}x{height_b}")
        print(f"bite_of_file:{filesize_before}KB>{filesize_after_size}KB")
    
elif args.mode == "reso":
    qualiti = args.quality
    if qualiti >= 100 or qualiti < 1:
        sys.exit("Invalid quality input.(Input allows 1~100 value)")
    
    img_reso_b = Image.open(filename)
    rereso_file = "reresoluted_" + filename
    img_reso_b.save(rereso_file, quality=qualiti)
    img_reso_b.close()
        
    filesize_after_reso = round(os.path.getsize(rereso_file) /1024, 2)
    if(args.util == 'debug'):
        print(f"{filesize_after_reso}")
    elif(args.util =='info'):
        print(f"bite_of_file:{filesize_before}KB>{filesize_after_reso}KB")
    
elif args.mode == "get":
    img_get = Image.open(filename)
    width_d,height_d = img_get.size
    if(args.util == 'debug'):
        print(f"{width_d},{height_d},{filesize_before}")
    else:
        print(f"size_of_file:{width_d}x{height_d}")
        print(f"bite_of_file:{filesize_before}KB")
else:
    sys.exit("Invalid input.")